# Generated by Django 3.2.5 on 2022-07-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_law'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawIno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64)),
                ('LawName', models.CharField(max_length=128)),
                ('KeyPoint', models.CharField(max_length=1024)),
                ('restrictedMode', models.CharField(max_length=16)),
                ('AgreementCountry', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Law',
        ),
    ]
