# Generated by Django 3.2.5 on 2022-07-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='casetitle',
            field=models.CharField(default=123, max_length=128),
            preserve_default=False,
        ),
    ]
