# Generated by Django 3.2.5 on 2022-07-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_cases_casetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='caseNeutralcoutryNumber',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cases',
            name='caseOpencoutryNumber',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cases',
            name='caseStrcitcoutryNumber',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
