# Generated by Django 3.2.5 on 2022-07-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20220720_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetUpCases',
            fields=[
                ('caseId', models.BigAutoField(primary_key=True, serialize=False)),
                ('UserInputId', models.CharField(max_length=32)),
                ('caseName', models.CharField(max_length=32)),
                ('caseScope', models.CharField(max_length=128)),
                ('caseInv', models.CharField(max_length=128)),
                ('caseInvEmail', models.CharField(max_length=128)),
                ('caseType', models.CharField(max_length=128)),
                ('casesynopsis', models.CharField(max_length=1000)),
            ],
        ),
    ]
