# Generated by Django 3.2.5 on 2022-07-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_setupcases_caseuserid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setupcases',
            old_name='caseUserId',
            new_name='caseUserName',
        ),
    ]
