# Generated by Django 3.2.5 on 2022-07-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_rename_caseuserid_setupcases_caseusername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('EvidenceId', models.BigAutoField(primary_key=True, serialize=False)),
                ('ComCaseId', models.CharField(max_length=32)),
                ('EvidenceType', models.CharField(max_length=32)),
                ('Principal', models.CharField(max_length=32)),
                ('EvidenceSummary', models.CharField(max_length=1000)),
            ],
        ),
    ]
