# Generated by Django 3.2.5 on 2022-07-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_evidence_evidencename'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='Source',
            field=models.CharField(default=123, max_length=32),
            preserve_default=False,
        ),
    ]
