# Generated by Django 3.2.5 on 2022-07-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_evidence_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='EvidenceLoc',
            field=models.CharField(default=111, max_length=32),
            preserve_default=False,
        ),
    ]
