# Generated by Django 3.2.5 on 2022-07-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_evidence_evidenceloc'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='ComCaseName',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
