# Generated by Django 3.2.5 on 2022-07-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_evidence_comcasename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('SourceId', models.BigAutoField(primary_key=True, serialize=False)),
                ('SourceName', models.CharField(max_length=32)),
                ('ComEvidenceId', models.CharField(max_length=32)),
                ('ComEvidenceName', models.CharField(max_length=32)),
                ('SourceType', models.CharField(max_length=32)),
                ('Manufacturer', models.CharField(max_length=32)),
                ('Model', models.CharField(max_length=32)),
                ('System', models.CharField(max_length=32)),
                ('SerialNumber', models.CharField(max_length=128)),
                ('AcquTool', models.CharField(max_length=32)),
            ],
        ),
    ]
