# Generated by Django 3.2.5 on 2022-07-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='Principal',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
