# Generated by Django 3.2.5 on 2022-07-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_source_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='Private',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
