# Generated by Django 3.2.5 on 2022-07-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_source_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='ComCaseId',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='ComCaseName',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
