# Generated by Django 3.2.5 on 2022-07-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_auto_20220729_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='Encryptionstatus',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
