# Generated by Django 3.2.5 on 2022-07-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_source_encryptionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userKey',
            field=models.CharField(default=11111, max_length=16),
            preserve_default=False,
        ),
    ]
