# Generated by Django 3.2.5 on 2022-08-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_user_userkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupcases',
            name='caseOriginCountry',
            field=models.CharField(default=111, max_length=32),
            preserve_default=False,
        ),
    ]
