# Generated by Django 3.2.5 on 2022-08-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_setupcases_caseorigincountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='lettername',
            field=models.CharField(default=111, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evidence',
            name='letterpath',
            field=models.CharField(default=111, max_length=100),
            preserve_default=False,
        ),
    ]
