# Generated by Django 3.2.5 on 2022-08-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_auto_20220813_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='lettername',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='letterpath',
        ),
    ]
