# Generated by Django 3.2.5 on 2022-08-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_auto_20220813_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='Eviletterpath',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
