# Generated by Django 3.2.5 on 2022-08-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_evidence_eviletterpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='warrant',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
