# Generated by Django 3.2.5 on 2022-08-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_source_warrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='justification',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
