# Generated by Django 3.2.5 on 2022-08-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_source_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='Attachment',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
